### ISSUE TITLE
[feature] Initializing the new Go client

### ISSUE THREAD

**Issue by JulienBreux** [microcks/microcks-go-client#1]
### Reason/Context

Hi awesome Microcks community!

Today, I want to propose the new Go client for Microcks.

_Regarding the contributing process, I start to open a new issue to describe the idea._

### Description

We need a strong Go client that following the Microcks core releases.

In this vision, I'd like to propose that the new Go client be generated using the Open API schemas.

My choice was the following tool: github.com/deepmap/oapi-codegen

In addition, we need to add some helpers to facilitate the go Client usage (for example missing enums, etc)

## Implementation

This is my idea of implementation: https://github.com/JulienBreux/microcks-client-go/tree/main

## How to use it?

```go
package main

import (
    "github.com/microcks/microcks-go-client"
)

const server = "http://localhost:8080/api"

fun main() {
	// Create client
	client, err := api.NewClientWithResponses(server)
	if err != nil {
		fatal(err)
	}

	// Request the Keycloak configuration
	ctx := context.Background()
	resp, err := c.actions.GetKeycloakConfigWithResponse(ctx)
	if err != nil {
		fatal(err)
	}

	// Print the response
	fmt.Printf("%+v\n\n", resp.JSON200)
}
```

I can also work with the owners of the Microcks project to get a much cooler package address.
For example: 

```go
import (
    "microcks.io/microcks-go-client"
)
```

(Just use the following meta `<meta name="go-import" content="...">`)

## Final note

Regarding the contributing process. After validation of this feature/idea, I will create the PR (+ roadmap of others ideas (live integration testing, etc...)).

**Comment by lbroudoux** [comment]
Hey Julien! 

I love your approach, as discussed previously. The nice thing is that we just published the 1.8 OpenAPI specification for Microcks API 😉  This one can be found here: https://github.com/microcks/microcks/blob/1.8.x/api/microcks-openapi-v1.8.yaml.

From what I understand, we'd just have to use this new reference and re-generate the client but ... I can't see any reference to the 1.7 version in config files or other ... Is there some kind of discovery mechanism that just uses what's found under the `/schema` folder?

I've got another question regarding the versioning scheme: how can we track the matching between version the `go-client` version and the API version? Should we include a `1.8` info in the title to inform it was generated from the `1.8`? How is this question usually handled in the Go community?

Many thanks for your contribution! Please go ahead with the PR! 👍

**Comment by JulienBreux** [comment]
> From what I understand, we'd just have to use this new reference and re-generate the client but ... I can't see any reference to the 1.7 version in config files or other ... Is there some kind of discovery mechanism that just uses what's found under the `/schema` folder?

Yes, that's a good idea.
In fact, I have two questions to answer:
1) Are we going to use classic SEMVER or version this client like Kubernetes? (https://github.com/kubernetes/client-go?tab=readme-ov-file#compatibility-matrix)
For Kubernetes Go client, we use `go get k8s.io/client-go@v0.20.4` (or obviously `go get k8s.io/client-go@latest`.
2) Is the client multi-version compatible, or does each version of the client represent the major version of Microcks?

My idea is to have the same things:
All yaml in `schema` folder BUT core branch like `1.7.x`, `1.8.x` to distribute for each version.

![image](https://github.com/microcks/microcks-go-client/assets/964330/712f153f-1615-4e64-81e7-09565837ba32)
![image](https://github.com/microcks/microcks-go-client/assets/964330/7b4021a0-f0ef-4672-be06-87f1e9c9fb25)

I use the idea of Kubernetes to avoid reinventing the wheel!

**Comment by lbroudoux** [comment]
Awesome!!!
